version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root